import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });
import ThemedToastContainer from "../components/ui/themed-toast-container";
import { GlobalStateProvider } from "../app/context/GlobalStateContext";
import { ThemeProvider } from "./providers/ThemeProvider";
import { THEME_BOOT_SCRIPT } from "../lib/theme/themeScript";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Find & Hire Trusted Tradespeople",
  description: "Generated by Turn Up Technologies",
  openGraph: {
    title: "Find & Hire Trusted Tradespeople",
    description: "Generated by Turn Up Technologies",
    url: `${process.env.NEXT_BASE_URL}`,  // Add your URL here
    images: [
      {
        url: `${process.env.NEXT_BASE_URL}/images/tradepeople-logo.png`,
        width: 1920,
        height: 1920,
        alt: "TradePeople logo",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Find & Hire Trusted Tradespeople",
    description: "Generated by Turn Up Technologies",
    images: [`${process.env.NEXT_BASE_URL}/images/tradepeople-logo.png`],
  },
};

export default function RootLayout({ children }) {

  //const redirectUri = "http://localhost:3000/login";
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Sets the theme class before first paint to avoid a flash of light. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOT_SCRIPT }} />
        <meta name="p:domain_verify" content="a27da9cfb864a326a9fbd3591af045a8" />
        <Script
          id="meta-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '575372878501776');
            fbq('track', 'PageView');
          `,
          }}
        />
        <Script
          id="clarity-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                c[a]("set", "cookieDomain", ".tradepeople.co.uk"); // Enables cross-subdomain tracking
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "on4vq32yvd");
            `,
          }}
        />
        <Script
          id="google-tag-manager"
          dangerouslySetInnerHTML={{
            __html: `
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-TFB5BR63');
          `,
          }}
        />
      </head>

      <body className={inter.className}>
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=GTM-TFB5BR63`}
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          />
          <img
            height="1"
            width="1"
            style={{ display: 'none' }}
            src="https://www.facebook.com/tr?id=575372878501776&ev=PageView&noscript=1"
            alt="Meta Pixel"
          />
        </noscript>
        <ThemeProvider>
          <ThemedToastContainer />
          <GlobalStateProvider>{children}</GlobalStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
